version: 2.1

references:
  container-config: &container-config
    docker:
    - image: circleci/clojure:openjdk-11-tools-deps-1.10.0.442-browsers

  restore-repo: &restore-repo
    restore_cache:
      keys:
        - repo-{{ .Branch }}-{{ .Revision }}
        - repo-{{ .Branch }}
        - repo

  deps-cache-key: &deps-cache-key
    deps-{{ checksum "deps.edn" }}

  restore-deps: &restore-deps
    restore_cache:
      keys:
        - *deps-cache-key
        
jobs:
  checkout-code:
    <<: *container-config
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  cljs-deps:
    <<: *container-config
    steps:
      - *restore-repo
      - run:
          name: Install dependencies
          command: clojure -e '(prn "Dependencies installed")'
      - save_cache:
          key: *deps-cache-key
          paths:
            - ~/.m2
            - .cpcache

  clj-kondo:
    <<: *container-config
    steps:
      - *restore-repo
      - run:
          name: Run Linter
          command: clojure -A:lint
          
  test:
    <<: *container-config
    steps:
      - *restore-repo
      - *restore-deps
      - run:
          name: Run tests on Headless Chrome
          command: clojure -A:fig:ci
          
workflows:
  version: 2
  build-test:
    jobs:
      - checkout-code
      - cljs-deps:
          requires:
            - checkout-code
      - clj-kondo:
          requires:
            - cljs-deps
      - test:
          requires:
            - cljs-deps
